{% set name = "tethys-platform" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tethysplatform/tethys/archive/refs/tags/{{ version }}.tar.gz
  sha256: 875ff1977c1dc37da31bcff1906d89d04fde45d7664252b0cb8655f18bbec35e

build:
  noarch: python
  number: 0
  entry_points:
    - tethys = tethys_cli:tethys_command
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.8
    - django >=3.2,<6
    - channels
    - daphne
    - setuptools_scm
    - pip
    - requests
    - bcrypt
    - pyyaml
    - jinja2
    - django-bootstrap5
    - django-model-utils
    - django-guardian
    - django-cors-headers
    - django-session-security
    - django-axes
    - django-gravatar2
    - django-simple-captcha
    - django-mfa2
    - django-recaptcha
    - social-auth-app-django
    - hs_restclient 
    - python-jose
    - django-oauth-toolkit
    - arrow
    - isodate
    - django-termsandconditions
    - django-analytical
    - django-json-widget
    - djangorestframework
    - PyShp
    - docker-py
    - conda
    - conda-libmamba-solver
    - postgresql
    - psycopg2 
    - sqlalchemy =1.*
    - geoalchemy2
    - plotly
    - bokeh
    - dask
    - condorpy
    - tethys_dask_scheduler >=1.0.2
    - tethys_dataset_services >=2.0.0
    - owslib 
    - siphon

test:
  requires:
    - pip
  imports:
    - tethys_apps
    - tethys_cli
    - tethys_compute
    - tethys_config
    - tethys_gizmos
    - tethys_portal
    - tethys_quotas
    - tethys_sdk
    - tethys_services
  commands:
    - tethys version
    - tethys gen portal_config --overwrite
    - tethys scaffold --defaults --overwrite test_app

about:
  home: http://www.tethysplatform.org/
  summary: A development platform for creating geospatial and scientific web applications.
  description: |
    Tethys Platform has been designed to lower the barrier to geospatial and 
    scientific web app development. Use it to deliver your models and data as 
    interactive web apps.
  license: BSD-2-Clause
  license_family: BSD
  license_file:
    - LICENSE
  doc_url: http://docs.tethysplatform.org/en/stable/
  dev_url: https://github.com/tethysplatform/tethys

extra:
  recipe-maintainers:
    - swainn
    - sdc50
